apiVersion: v1
kind: Pod
metadata:
  name: nginx-edge1
spec:
  nodeName: edge-amine1
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-edge2
spec:
  nodeName: edge-amine2
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80