apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment004
  labels:
    app: nginx
  annotations:
    argocd.argoproj.io/hook: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80