---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-wan-mpls-1-edge1
  namespace: namla-system
  labels:
    controlled-by: amine
spec:
  address: 10.25.10.202/24
  ifname: ens5
  nodename: edge1
  nvni-name: nvni-2
  type: WAN
  control-plane:
    bgp-as: 64513
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkFunction
metadata:
  name: cnf-lan-lan-2-edge1
  namespace: namla-system
  labels:
    controlled-by: amine
spec:
  address: 10.25.22.76/24
  ifname: ens4
  nodename: edge1
  nvni-name: nvni-1
  type: LAN
  #stn: true
  control-plane:
    bgp-as: 64514
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkControllerVpnProfile
metadata:
  name: cnf-vpn-profile-cnf-wan-mpls-1-edge1
  namespace: namla-system
  labels:
    controlled-by: amine
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    controllerId:
      id: mediator@namla.com
      type: RFC822_ADDR
    controllerIpAddress: 13.38.23.122
    localId:
      id: cnf-wan-mpls-1-edge1@namla.cloud
      type: RFC822_ADDR
    authentication:
      type: psk
      name: controller1-cnf
      key: password
---
apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkLinuxRoute
metadata:
  name: cnf-default-route-cnf-wan-mpls-1-edge1
  namespace: namla-system
  labels:
    controlled-by: amine
spec:
  nodename: edge1
  cnf: cnf-wan-mpls-1-edge1
  config:
    scope: GLOBAL
    dst_network: 0.0.0.0/0
    gw_addr: 10.25.10.37
    metric: 0